version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  AfterInstall:
    - location: scripts/install_build.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
