import { Request, Response } from "express"
import { CTESchool } from "../models/cte_school.model"
import { SchoolDistricts } from "../models/school_district.model"
import { Student } from "../models/student.model"
import sequelize from "../database"
